
doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        server_version: '16'

        profiling_collect_backtrace: '%kernel.debug%'
        types:
            uuid: Symfony\Bridge\Doctrine\Types\UuidType
    orm:
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        identity_generation_preferences:
            Doctrine\DBAL\Platforms\PostgreSQLPlatform: identity
        auto_mapping: true
        mappings:
            Receipt:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Receipt/Infrastructure/Persistence/Doctrine/Entity'
                prefix: 'App\Receipt\Infrastructure\Persistence\Doctrine\Entity'
                alias: Receipt
            Station:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Station/Infrastructure/Persistence/Doctrine/Entity'
                prefix: 'App\Station\Infrastructure\Persistence\Doctrine\Entity'
                alias: Station
            User:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/User/Infrastructure/Persistence/Doctrine/Entity'
                prefix: 'App\User\Infrastructure\Persistence\Doctrine\Entity'
                alias: User
            Import:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Import/Infrastructure/Persistence/Doctrine/Entity'
                prefix: 'App\Import\Infrastructure\Persistence\Doctrine\Entity'
                alias: Import
            Vehicle:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Vehicle/Infrastructure/Persistence/Doctrine/Entity'
                prefix: 'App\Vehicle\Infrastructure\Persistence\Doctrine\Entity'
                alias: Vehicle
            Admin:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Admin/Infrastructure/Persistence/Doctrine/Entity'
                prefix: 'App\Admin\Infrastructure\Persistence\Doctrine\Entity'
                alias: Admin
            Maintenance:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Maintenance/Infrastructure/Persistence/Doctrine/Entity'
                prefix: 'App\Maintenance\Infrastructure\Persistence\Doctrine\Entity'
                alias: Maintenance
        controller_resolver:
            auto_mapping: false

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
