# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
# See also https://symfony.com/doc/current/service_container/import.html

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.jwt_secret: '%env(JWT_SECRET)%'
    app.jwt_ttl_seconds: '%env(int:JWT_TTL_SECONDS)%'
    app.import.storage_name: 'local'
    app.import.storage_dir: '%kernel.project_dir%/%env(string:APP_SHARE_DIR)%/imports'
    app.geocoding.nominatim_base_uri: '%env(string:NOMINATIM_BASE_URI)%'
    app.geocoding.nominatim_user_agent: '%env(string:NOMINATIM_USER_AGENT)%'
    app.geocoding.nominatim_email: '%env(default::NOMINATIM_EMAIL)%'
    app.oidc_providers:
        auth0:
            enabled: '%env(bool:OIDC_AUTH0_ENABLED)%'
            label: 'Auth0'
            issuer: '%env(string:OIDC_AUTH0_ISSUER)%'
            client_id: '%env(string:OIDC_AUTH0_CLIENT_ID)%'
            client_secret: '%env(string:OIDC_AUTH0_CLIENT_SECRET)%'
            scopes: ['openid', 'profile', 'email']
        google:
            enabled: '%env(bool:OIDC_GOOGLE_ENABLED)%'
            label: 'Google'
            issuer: '%env(string:OIDC_GOOGLE_ISSUER)%'
            client_id: '%env(string:OIDC_GOOGLE_CLIENT_ID)%'
            client_secret: '%env(string:OIDC_GOOGLE_CLIENT_SECRET)%'
            scopes: ['openid', 'profile', 'email']
        microsoft:
            enabled: '%env(bool:OIDC_MICROSOFT_ENABLED)%'
            label: 'Microsoft'
            issuer: '%env(string:OIDC_MICROSOFT_ISSUER)%'
            client_id: '%env(string:OIDC_MICROSOFT_CLIENT_ID)%'
            client_secret: '%env(string:OIDC_MICROSOFT_CLIENT_SECRET)%'
            scopes: ['openid', 'profile', 'email']

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    App\Shared\Infrastructure\Serializer\UuidNormalizer:
        tags:
            - { name: 'serializer.normalizer', priority: 100 }

    App\Security\JwtTokenManager:
        arguments:
            $jwtSecret: '%app.jwt_secret%'
            $jwtTtlSeconds: '%app.jwt_ttl_seconds%'

    App\Security\Oidc\OidcProviderRegistry:
        arguments:
            $providersConfig: '%app.oidc_providers%'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\Station\Application\Geocoding\Geocoder: '@App\Station\Infrastructure\Geocoding\NominatimGeocoder'
    App\Station\Infrastructure\Geocoding\NominatimGeocoder:
        arguments:
            $nominatimHttpClient: '@http_client'
            $nominatimRateLimiter: '@limiter.nominatim_geocoding'
            $baseUri: '%app.geocoding.nominatim_base_uri%'
            $cache: '@cache.app'
            $userAgent: '%app.geocoding.nominatim_user_agent%'
            $contactEmail: '%app.geocoding.nominatim_email%'
    App\Import\Application\Storage\ImportFileStorage: '@App\Import\Infrastructure\Storage\LocalImportFileStorage'
    App\Import\Infrastructure\Storage\LocalImportFileStorage:
        arguments:
            $storageName: '%app.import.storage_name%'
            $baseDirectory: '%app.import.storage_dir%'
    App\Receipt\Application\Repository\ReceiptRepository: '@App\Receipt\Infrastructure\Persistence\Doctrine\Repository\DoctrineReceiptRepository'
    App\Import\Application\Repository\ImportJobRepository: '@App\Import\Infrastructure\Persistence\Doctrine\Repository\DoctrineImportJobRepository'
    App\Station\Application\Repository\StationRepository: '@App\Station\Infrastructure\Persistence\Doctrine\Repository\DoctrineStationRepository'
